Error message: Traceback (most recent call last):
  File "/home/dbyl/pepper-best-deals/source/pepper_app/populate_database.py", line 62, in load_to_db
    pepperarticle_obj, _ = PepperArticle.objects.get_or_create(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/home/dbyl/pepper-best-deals/env/lib/python3.10/site-packages/pytest_django/plugin.py", line 780, in _blocking_wrapper
    raise RuntimeError(
RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
, Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it. 
